#!/bin/bash

[[ -z $1 ]] && echo 'no arg provided. provide an INT for workspace.' && exit 1

target=$1

IFS=$'\n'
workspaces=($(i3-msg -t get_workspaces | grep -Po '(?:num":)(\d\d)?.*?visible":(true|false)' | sed 's/,/:/g' | cut -d':' -f2,6 ))

unset IFS

active=""
for i in ${workspaces[@]}; do
    if [[ $i =~ 'true' ]]; then
	active=${i%%:*}
	echo $active
	break
    fi
done

i3-msg "rename workspace $active to temp; rename workspace $target to $active; rename workspace temp to $target; "

	
	

